name: Build

on:
  push:
    branches: [ master, feature/** ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, android]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Install fyne-cross compiler
      run: go install github.com/fyne-io/fyne-cross@latest
    - name: Install fyne
      run: go install fyne.io/fyne/v2/cmd/fyne@latest
    - name: Build
      run: fyne-cross ${{ matrix.os }} -app-id org.fairdatasociety.fairpass -icon icon.png
