name: build

on:
  push:
    branches: [ master, feature/** ]
  pull_request:
    branches: [ master ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Install fyne
      run: go install fyne.io/fyne/v2/cmd/fyne@latest
    - name: Install fine-cross compiler
      run: go install github.com/fyne-io/fyne-cross@latest    
    - name: Build
      run: fyne-cross linux --app-id org.fairdatasociety.fairpass
    
